### PR TITLE
Hooks for React

### PR DESCRIPTION
**Pull request by d3x7r0**
While working on a personal project using redux-zero I started playing around with implementing hooks for use with the library so I cleaned them up, added some tests, an example, and here they are.

Using them would be something like this:
```jsx harmony
const Counter = () => {
  const store = useStore()
  const count = useSelector(({ count }) => count)
  const incrementBy = useAction(({ count }, value) => ({ count: count + value}))

  return (
    <>
      <p>Value: {count}</p>
      <button onClick={() => incrementBy(10)}>10 More</button>
    </>
  )
}
```

- `useStore` returns the store straight from the provider
- `useSelector` works roughly the same way as the `mapStateToProps` function. It's perfectly acceptable to use props inside the closure and the resulting value will be cached if it's strictly equal to previous versions but the selector function itself will be called multiple times so it can be a performance pitfall.
 - `useAction` binds an action to the store and returns it.

I would very much appreciate feedback on this one. I mostly followed the nomenclature set out by Redux wherever possible and did reference their implementation to try and avoid some common pitfalls but I'm not sure the naming is the best for redux-zero. I'm not particularly fond of the `useSelector` naming and the way it works actually. Maybe it would be better to get an array of inputs like `useMemo` when using props inside the selector function?

### CODE REVIEW

**Comment by matheusml** [comment]
This seems incredible! Thanks for that.

But before I can take a look, could you please solve the conflicts and update the npm version/changelog?

Also, is this a breaking change?

**Comment by d3x7r0** [comment]
I did try running the react examples using the old minimum version and they worked fine. Of course the hooks themselves don't work but that's expected.

**Comment by ernaneluis** [comment]
any update on this?

**Comment by d3x7r0** [comment]
From my side everything seems fine. I tried running the example with the old react version and had no issues at all.

**Pull request merged**
